### ISSUE TITLE
[React] 5장 ref:DOM에 이름 달기 (#2)

### ISSUE THREAD

**Issue by minsook8280** [minsook8280/study_react_old#11]
일반 HTML에서 DOM요소에 이름을 달 때는 id를 사용한다.
```
<div id="my-element"></div>
```
리액트 프로젝트 내부에서 DOM에 이름을 다는 방법은 ref (reference의 줄임말) 개념이다. 

> 리액트 컴포넌트안에서도 id를 상ㅇ할 수는 있지만, id는 유일해야 하는데 컴포넌트를 여러번 사용하게되면 중복 id를 가진 DOM이 여러게 생기니 잘못된 사용이다.
> ref는 전역적으로 작동하지 않고 컴포넌트 내부에서만 작동하기 때문에 이러한 문제가 발생하지 않는다.

## 5.1 ref는 어떤 상황에서 사용해야 할까?
**DOM을 꼭 직접적으로 건드려야 할 때** ref를 사용한다.

클래스형 컴포넌트에서  ref를 사용하는 방법

### 5.1.1 예제 컴포넌트 생성

ValidationSample.css
```
.success {
    background-color: lightgreen;
}
.failure {
    background-color: lightcoral;
}
```

ValidationSample.js
```
import React, { Component } from 'react';
import './ValidationSample.css';

class ValidationSample extends Component {
    state = {
        password: '',
        clicked: false,
        validated: false
    }

    handleChange = (e) => {
        this.setState({
            password: e.target.value
        });
    }

    handleButtonClick = () => {
        this.setState({
            clicked: true,
            validated: this.state.password === '0000'
        })
    }

    render() {
        return (
            <div>
                <input 
                    type="password"
                    value={this.state.password}
                    onChange={this.handleChange}
                    className={this.state.clicked ? (this.state.validated ? "success" : "failure") : ''}
                />
                <button onClick={this.handleButtonClick}>검증하기</button>
            </div>
        )
    }
}

export default ValidationSample;
````
input에서 onChange이벤트 발생하면 handleChange호출해서 state의 password값을 업데이트.
button에서는 onClick이벤트 발생하면 handleButtonClick 호출하여 clicked값을 true로 설정하고 validated값을 검증결과로 설정.
input의 className값은 버튼 누리기전에는 비어있는 문자열 전달하며 버튼누른후에는 검증 결과에 따라 success또는 failure값 전달하면서 색상도 변경된다.

### 5.1.2 App컴포넌트에서 예제 컴포넌트 렌더링
App컴포넌트에서 ValidationSample컴포넌트를 불러올 때 App컴포넌트를 클래스형 컴포넌트로 전환하기
```
import React, { Component } from 'react';
import ValidationSample from './ValidationSample';

class App extends Component {
  render() {
    return(
      <ValidationSample />
    );
  }
}
export default App;
```
### 5.1.3 DOM을 꼭 사용해야 하는 상황
state만으로 필요한 기능을 구현할 수 없을때 DOM에 직접적으로 접근하기 위해 ref를 사용한다.
- 특정 input에 포커스 주기
- 스크롤 박스 조작하기
- Canvas요소에 그림 그리기 등

### 5.2.1 콜백 함수를 통한 ref 설정
ref를 만드느 가장 기본적인 방법은 콜백함수를 사용하는 것.
ref를 달고자 하는 요소에 ref라는 콜백함수를 props로 전달해 준다. 이 콜백 함수는 ref값을 파라미터로 전달 받는다. 그리고 함수 내부에서 파라미터로 받은 ref를 컴포넌트의 멤버 변수로 설정해준다.
```
// 콜백함수 사용 예시
<input ref={(ref) = > {this.input=ref}} />
```
여기서 this.input은 input요소의  DOM을 가리킨다. ref이름은 자유롭게 지정 가능.

### 5.2.2 createRef를 통한 ref설정
ref를 만드는 또 다른 방법은 리액트에 내장되어 있는 createRef 함수를 사용하는 것.

createRef사용 예시
```
import React, { Component } from 'react';

class RefSample extends Component {
    input = React.createRef();

    handleFocus = () => {
        this.input.current.focus();
    }

    render() {
        return(
            <div>
                <input ref={this.input} />
            </div>
        )
    }
}
export default RefSample;
```
createRef를 사용하여 ref를 만들려면 우선 컴포넌트 내부에서 멤버 변수로 React.createRef()를 담아주어야 한다. 그리고 해당 멤버 변수를 ref를 달고자 하는 요소에 ref props로 넣어주면 된다.
설정 후 ref를 설정해준 DOM에 접근하려면 this.input.current를 조회하면 된다.
콜백함수와 다른 점은 뒷부분에 .current를 넣어주어야 한다는것.

### 5.2.3 적용
input요소를 클릭하면 포커스가 되면서 텍스트 커서가 깜박거림.
버튼을 누르면 포커스가 버튼으로 넘어가서 왼쪽 input요소의 텍스트 커서가 더이상 보이지 않는다. 

버튼을 한 번 눌렀을 때, 포커스가 다시 input쪽으로 자동으로 넘어가게 해보자.

#### 5.2.3.1 input에 ref 달기
콜백함수를 사용하여 ValidationSample 컴포넌트에 ref 달아보자
```
<input 
                    ref={(ref) => this.input = ref}
                    type="password"
                    value={this.state.password}
                    onChange={this.handleChange}
                    className={this.state.clicked ? (this.state.validated ? "success" : "failure") : ''}
                />
```

#### 5.2.3.2 버튼 onClick 이벤트 코드 수정
버튼에서 onClick 이벤트가 발생할 때 input에 포커스를 주도록 코드 수정.
```
handleButtonClick = () => {
        this.setState({
            clicked: true,
            validated: this.state.password === '0000'
        });
        this.input.focus();
    }
```
확인 버튼 클릭후 포커스가 input으로 바로 넘어간다.

## 5.3 컴포넌트에 ref 달기
컴포넌트 내부에 있는 DOM을 컴포넌트 외부에서 사용할 때 컴포넌트에도 ref를 달 수 있다.
방법은 DOM에 ref를 다는 방법과 동일.

### 5.3.1 사용법
```
// MyComponent 내부의 메서드 및 멤버 변수에도 접근 가능
<MyComponent
    ref={(ref) => {this.myComponet=ref}}
/>
```

스크롤 박스가 있는 컴포넌트를 만들고, 스크롤바를 아래로 내리는 작업을 부모 컴포넌트에서 실행하기

## 5.3.2 컴포넌트 초기 설정
ScrollBox.js
```
import React, { Component } from 'react';

class ScrollBox extends Component {
    render() {
        const style = {
            border: '1px solid black',
            height: '300px',
            width: '300px',
            overflow: 'auto',
            position: 'relative'
        };

        const innerStyle = {
            width: '100%',
            height: '650px',
            background: 'linear-gradient(white, black)'
        }

        return(
            <div
                style={style}
                ref={(ref) => {this.box=ref}}>
                <div style={innerStyle} />
            </div>
        )
    }
}
export default ScrollBox;
```

#### 5.3.2.2 App컴포넌트에서 스크롤 박스 컴포넌트 렌더링
```
import React, { Component } from 'react';
import ScrollBox from './ScrollBox';

class App extends Component {
  render() {
    return(
      <ScrollBox />
    );
  }
}
export default App;
```

_여기까지 ref를 달기 전후 코드의 차이 모르겠음;;;;;;;;;;;_

### 5.3.3 컴포넌트에 메서드 생성
컴포넌트에 스크롤바를 맨 아래쪽으로 내리는 메서드를 만들자.
자바스크립트로 스크롤바를 내릴 때는 DOM노드가 가진 다음 값들을 사용한다.
- scrollTop : 세로 스크롤바 위치(0~350)
- scrollHeight :스크롤이 있는 박스 안의 div높이(650)
clientHeight : 스크롤이 있는 박스의 높이(300)

ScrollBox.js
```
import React, { Component } from 'react';

class ScrollBox extends Component {
    scrollToBottom = () => {
        const { scrollHeight, clientHeight } = this.box;
        this.box.scrollTop = scrollHeight - clientHeight;
    }
    render() {
        const style = {
            border: '1px solid black',
            height: '300px',
            width: '300px',
            overflow: 'auto',
            position: 'relative'
        };

        const innerStyle = {
            width: '100%',
            height: '650px',
            background: 'linear-gradient(white, black)'
        }

        return(
            <div
                style={style}
                ref={(ref) => {this.box=ref}}>
                <div style={innerStyle} />
            </div>
        )
    }
}
export default ScrollBox;
```

### 5.3.4 컴포넌트에 ref 달고 내부 메서드 사용
App컴포넌트에서 ScrollBox에 ref를 달고 버튼을 누르면, ScrollBox 컴포넌트의  ScrollToBottom 메서드 실행하기

App.js
```
import React, { Component } from 'react';
import ScrollBox from './ScrollBox';

class App extends Component {
  render() {
    return(
      <div>
        <ScrollBox ref={(ref) => this.scrollBox=ref} />
        <button onClick={() => this.scrollBox.scrollToBottom()}>
          맨 밑으로
        </button>
      </div>
    );
  }
}
export default App;
```

## 5.4 정리
컴포넌트 내부에서 DOM에 직접 접근해야 할 때는 ref를 사용.
서로 다른 컴포넌트끼리 데이터 교류를 할 때 ref사용은 리액트 사상에 어긋난 설계로 지양.
컴포넌트끼리 데이터 교류시에는 부모 <-> 자식 흐름으로 교류해야함.
함수형 컴포넌트에서의 ref사용은 useRef라는 Hool함수를 사용.

**Comment by hyeonmi** [comment]
ref를 활용하는 이유가 `5.2.3.2 버튼 onClick 이벤트 코드 수정` 경우에는 아래 한줄 스펙을 구현하기 위해서 필요합니다.
```js
this.input.focus();
```
그리고 `5.3.2.2 App컴포넌트에서 스크롤 박스 컴포넌트 렌더링` 에서 차이점을 모르겠다고 하셨는데 이전 코드까지가 스펙이면 ref를 사용하지 않아도 됩니다. (차이점이 없는게 맞아요.)
다만 스크롤 위치를 변경해야하는 스펙이 있다면 추가해서 이후 코드 부분을 구현해야합니다.
```js
    scrollToBottom = () => {
        const { scrollHeight, clientHeight } = this.box;
        this.box.scrollTop = scrollHeight - clientHeight;
    }
```
