### ISSUE TITLE
[React] 1장 리액트 시작 (#1)

### ISSUE THREAD

**Issue by minsook8280** [minsook8280/study_react_old#7]
## 1.1 왜 리액트인가?
자바스크립트만으로도 규모가 큰 애플리케이션을 만들 수 있는 시대가 왔다. 
Angular, Backbone.js, Derby.js, Ember.js, Ext.js, Knockback.js, Sammy.js, PureMVC, Vue.js 등 수많은 프레임워크들이 대규모 애플리케이션중 프런트엔드 사이드에서 돌아가는 애플리케이션 구조를 관리하기 위해 노력해 왔다. 
이 프레임워크들은 주로 MVC(Model-View-Controller)아키텍쳐, MVVM(Model-View-View Model)아키텍처를 사용한다. 
이들의 공통점은 모델(Model)과 뷰(View)가 있다는 것.
- 모델(Model)은 애플리케이션에서 사용하는 데이터를 관리하는 영역.
- 뷰(View)는 사용자에게 보이는 부분.
페이스북 개발팀이 어떤 데이터가 변할 때마다 기존 뷰를 날려 버리고 처음부터 새로 렌더링하는 방식으로 최대한 성능을 아끼로 편안한 사용자 경험을 제공하면서 구현한 것이 리액티(React)이다.

### 1.1.1 리액트 이해
리액트는 자바스크립트 라이브러리로 사용자 인터페이스를 만드는데 사용.
구조가 MVC, MVW 등인 프레임워크와 달리, **오직 V(View)만 신경쓰는 라이브러리**.

**컴포넌트**
리액트 프로젝트에서 특정 부분이 어떻게생길지 정하는 선언체.
다른 프레임워크에서 사용자 인터페이스를 다룰 때 사용하는 템플릿과 다른 개념.
컴포넌트는 재사용이 가능한 API로 수많은 기능을 내장하고 있으며, 컴포넌트 하나에 해당 컴포넌트의 생김새와 작동방식을 정의한다.

**렌더링**
사용자 화면에서 뷰를 보여주는 것.
리액트 컴포넌트가 최초로 실행한 **"초기 렌더링"** 과 컴포넌트의 데이터 변경이 다시 실행되는 **"리렌더링"** 개념을 이해해야 리액트 라이브러리가 데이터가 변할 때마다 뷰를 새롭게 리렌더링하면서 성능을 아끼고, 최적의 사용자 경험을 제공하는지 이해할 수 있다.

#### 1.1.1.1 초기 렌더링
맨 처음 어떻게 보일지를 정하는 초기렌더링이 필요한데, 리액트에서는 이를 다루는 **render함수** 가 있다.
```
render() {...}
```
- render함수는 컴포넌트가 어떻게 생겼는지를 정의하는 역할을 한다.
- html 형식의 문자열을 반환하지 않고, 뷰가 어떻게 생겼고 어떻게 작동하는지에 대한 정보를 지닌 객체를 반환한다.
- 컴포넌트 내부에 또 다른 컴포넌트들이 들어갈 수 있다.
- render함수를 실행하면 그 내부에 있는 컴포넌트들도 재귀적으로 렌더링한다.
- 최상위 컴포넌트의 렌더링 작업이 끝나면 지니고 있는 정보를 사용하여 HTML마크업을 만들고, 이를 우리가 정하는 실제 페이지의 DOM요소 안에 주입한다.

#### 1.1.1.2 조화과정
리액트에서 뷰를 업데이틀 할때는 "조화 과정(reconciliation)을 거친다"라고 표현하는것이 정확하다.
컴포넌트는 데이터를 업데이트했을 때 단순히 업데이트 한 값을 수정하는 것이 아니라, 새로운 데이터를 가지고 render함수를 또 다시 호출한다. 즉 새로운 요소로 갈아끼우는 것.
이때 render함수가 반환하는 결과를 곧바로 DOM에 반영하지 않고, 이전 render함수가 만들었던 컴포넌트 정보와 현재 render함수가 만든 컴포넌트 정보를 비교한 후, 둘의 차이를 알아내 최소한의 연산으로 DOM트리를 업데이트한다.
결국 방식 자체는 루트 노드부터 시작하여 전체 컴포넌트를 처음부터 다시 렌더링 하는것 처럼 보이지만, 사실 최적의 자원을 사용하여 이를 수행하는 것이다.

#### 1.2.1.1 DOM이란?
DOM은 Document Object Model, 객체로 문서 구조를 표현하는 방법으로 XML이나 HTML로 작성한다.
DOM은 트리 형태라서 특정 노드를 찾거나 수정하거나 제거하거나 원하는 곳에 삽입할 수 있다.

**DOM은 과연 느릴까?**
동적 UI에 최적화 되어 있지않다. 
HTML은 자체적으로 정적이므로 자바스크립트를 사용하여 동적으로 만들 수 있다.
대규모 웹 애플리케이션에서 DOM에 직접 접근하여 변화를 주다보면 성능 이슈가 발생한다. 이는 DOM자체가 느린것이 아니라 DOM을 읽고 쓸 때 웹브라우저가  css를 다시 연산하고, 레이아웃을 구상하고, 페이지를 리페인트하는 과정에 시간이 걸리는 것이다

**해결법**
리액트는 Virtual DOM방식을 사용하여 DOM업데이트를 추상화함으로써 DOM처리 횟수를 최소화하고 효율적으로 진행한다.

#### 1.2.1.2 Virtual DOM
Virtual DOM을 사용하면 실제 DOM에 접근하여 조작하는 대신, 이를 추상화한 자바스크립트 객체를 구성하여 사용. 실제 DOM의 가벼운 사본과 비슷.

**웹브라우저에서 실제 DOM을 업데이트 할때 절차**
1. 데이터를 업데이트하면 전체 UI를 Virtual DOM에 리렌더링한다.
2. 이전 Virtual DOM에 있던 내용과 현재 내용을 비교한다.
3. 바뀐 부분만 실제 DOM에 적용한다.

**오해**
Virtual DOM을 사용한다고 해서 사용하지 않을 때와 비교하여 무조건 빠른것으 아니다. 
지속적으로 데이터가 변화하는 대규모 어플리케이션을 구축할 때 비로소 리액트가 지닌 진가를 발휘할 수 있다.

### 1.2.2 기타 특징
리액트는 오직 뷰만 담당하는 라이브러리이므로 기타 기능은 직접 구현하여 사용해야 한다. 하지만 다른 개발자들이 만든 라이브러리(라우팅에는 리액트 라우터, Ajax처리에는 axios나 fetch, 상태관리에는 리덕스나 MobX 등)를 사용하여 자신의 취향대로 스택을 설정할 수 있다. 하지만 여러 라이브러리를 접해야 한다는 단점도 있다.
또 리액트는 다른 웹 프레임워크나 라이브러리와(Backbone.js, AngularJS 등) 혼용할 수도 있다.

## 1.3 작업 환경 설정

내용 생략

**Comment by hyeonmi** [comment]
-  MVC(Model-View-Controller)아키텍쳐, MVVM(Model-View-View Model)아키텍처 대해 설명해주세요.
- Virtual DOM 도 많이 물어 보는 개념 중에 하나에요.

**Comment by minsook8280** [comment]
## MVC(Model-View-Controller) 아키텍처

### Controller
중간자 역할.
클라이언트로부터 요청(Request)이 들어올 경우, 요청에 대해서 실제 업무를 수행하는 모델(Model) 컴포넌트를 호출하는 일을 한다. 만약 클라이언트가 보낸 데이터가 있다면 모델에 전달하기 쉽도록 데이터를 가공하며, 모델이 업무를 마치면 그 결과로 화면을 생성하도록 뷰에게 전달하는 일을 한다.

### Model
데이터를 처리.
컨트롤러(Controller)로부터 요청이 들어올 경우, DB에 연결을 해서 원하는 데이터를 가져오거나 변경(수정, 생성, 삭제)작업을 진행하게 된다.

### View
화면을 만든다.
모델이 처리한 데이터를 가지고 사용자에게 보여줄 화면을 만드는 일을 한다. 만들어진 화면은 웹 브라우저를 통해 사용자에게 보여진다. 즉 뷰는 HTML, CSS, JAVASCRIPT를 이용하여 사용자가 볼 수 있는 UI를 만든다.

## MVVM(Model-View-ViewModel) 아키텍처
### Model
UI에 표시될 데이터 와 비즈니스 로직을 담당

### View
UI(화면)을 만든다.

### ViewModel
이벤트 처리나, Model과의 인터랙션 등을 담당한다.

## MVC 아키텍처와 MVVM 아키텍처의 차이
- MVC 구조에서는 컨트롤러가 뷰와 연결되어 유저와 상호작용도 하고, 모델과도 연결되어 데이터도 처리했다. 즉 뷰와 모델 사이에서 중재자 역할을 했다. 예를 들어 컨트롤러가 유저의 클릭 액션을 확인하고, 모델에 데이터를 갱신하도록 요청하고, 뷰에도 화면을 업데이트 하라고 요청을 해야한다. 코딩하다 무언가 빠뜨리면, 때로는 DB만 갱신되고 화면은 갱신되지 않는 경우도 나타난다.
- MVVM 구조에서는 뷰에서 뷰모델로, 뷰모델에서 모델로 작업을 처리하며, 뷰에서 모델을 직접 참조하지 않는다. 대신 뷰에서 뷰모델을 관찰하며 데이터의 변경 사항을 감지한다. 예를들어 MVVM에서도 뷰가 유저의 클릭 액션을 확인하지만, 뷰에서 곧바로 DB에 접근하지 않는다. 말 그대로 ‘뷰’이기 때문에 UI를 갱신하는 역할에 충실하다. 대신 뷰모델을 참조하고, 뷰모델에서는 다시 모델에서 잘 정리된 데이터를 참조한다. 또, 뷰는 뷰모델을 관찰(Observe) 한다. DB에 새로운 아이템을 추가한 후에 화면을 업데이트 하라고 직접 명령하지 않아도 된다. 뷰에서는 이미 뷰모델을 관찰하고 있기 때문에 데이터의 변화를 알아차리고 자동으로 화면을 갱신한다.

**Comment by hyeonmi** [comment]
@minsook8280 님 다음 오프라인 모임때 이 개념 강의한번 해주실래요?
